### ISSUE TITLE
Clearer documentation on order of .use()

### ISSUE THREAD

**Issue by nthgol** [helmetjs/nocache#16]
I just found out experimentally that `app.use(nocache())` must come before `app.use('/path/to/routes', routes)` when exporting an app. Otherwise, the headers don't get added to all those routes. 

Can you please just add 1 clause for future users? 

Thanks

**Comment by EvanHahn** [comment]
Hmm, that's surprising. What headers are you seeing?

**Comment by nthgol** [comment]
everything i'd see if I didn't have the nocache headers.

**Comment by EvanHahn** [comment]
Please do—I'd love to know why `nocache`'s headers are being overridden.

**Comment by nthgol** [comment]
### No Bug
Chrome tools with correct headers:
![image](https://user-images.githubusercontent.com/26420958/48855353-e5fe1c00-ed81-11e8-9ce0-02a26b9a863d.png)
Code:
```
const express = require('express');
const bodyParser = require('body-parser');
const cors = require('cors');
const routes = require('../api/routes/index.route');
const { handler } = require('../api/middleware/errorHandler');
const ev = require('express-validation');
const nocache = require('nocache');

const app = express();

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: false }));

app.use(cors());
app.use(nocache());
app.use('/api/v1', routes);
app.use(handler);
app.set('etag', 'strong');
```

### Bug
Network with incorrect headers
![image](https://user-images.githubusercontent.com/26420958/48855482-22317c80-ed82-11e8-8c49-2b2e227b989a.png)

Code:
```
//same as above
app.use('/api/v1', routes);
app.use(nocache());
//same as above
```

**Comment by EvanHahn** [comment]
I'm pretty sure that's happening because `nocache` is being `use`d *after* your routes file, not before. Could you try reordering your middleware usage?

**Comment by nthgol** [comment]
No that makes sense - I forgot that top-level middleware (ie not in routers ) is also order-sensitive. Responses are sent in the routes, so it never gets to `nocache()`.

**Comment by EvanHahn** [comment]
Glad we solved it. Let me know if I can help with anything else!
