### ISSUE TITLE
Just `no-store`

### ISSUE THREAD

**Issue by Jxck** [helmetjs/nocache#19]
In RFC defined that `no-store` just specifies don't store a response in any cache and others in current implementations seems conflicted.

Why no just set only `no-store` in `Cache-Control` ?

**Comment by EvanHahn** [comment]
Good question.

I can't find any reference to this in a few minutes of searching, but I recall that we set a bunch of directives for wider support. Various browsers, proxies, and HTTP tools have differing support here.

That might be wrong, though!

**Comment by EvanHahn** [comment]
I'm going to close this issue because I don't think there's action to be taken here.

If that's wrong, let me know and I'll reopen.

**Comment by Jxck** [comment]
I see, thanks.

**Comment by KylerD** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#preventing_caching reading that I thought the same thing @Jxck
