### ISSUE TITLE
Cache-Control should include private

### ISSUE THREAD

**Issue by bobzoller** [helmetjs/nocache#2]
Seems like the `Cache-Control` header should include `private`.  Per [RFC2616 14.9.1](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html):

> **private**: Indicates that all or part of the response message is intended for a single user and MUST NOT be cached by a shared cache. This allows an origin server to state that the specified parts of the response are intended for only one user and are not a valid response for requests by other users. A private (non-shared) cache MAY cache the response.

Caches like [varnish](https://www.varnish-cache.org/) will happily cache the current response, but would not if `private` were included.

Thoughts?

**Comment by EvanHahn** [comment]
This is a good idea.

Do we want this to be (1) on be default (2) configurable?

**Comment by bobzoller** [comment]
I vote on by default, not configurable.  If the rest of it isn't
configurable, this probably doesn't need to be.

**Comment by EvanHahn** [comment]
Agreed.

I'm reading through the spec again to see if there's a particular order it
needs to be in.

**Comment by makebbekus** [comment]
Ah great! I was just coming to make the same request to add `private`!

**Comment by bobzoller** [comment]
small world!

On Thu, Apr 23, 2015 at 10:30 AM, Michael Kebbekus <notifications@github.com

**Comment by EvanHahn** [comment]
Fixed! Pushed `nocache@0.3.0` and `helmet@0.9.0`.

**Comment by bobzoller** [comment]
Killer thanks Evan!
