### ISSUE TITLE
Removal of Pragma Header 

### ISSUE THREAD

**Issue by dani2819** [helmetjs/nocache#25]
It has come to my attention that the Pragma header is no longer recommended as per the latest web standards and may already have been removed, be in the process of being dropped, or only kept for compatibility purposes. For more information: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Pragma

The Pragma header was initially used to provide backward compatibility with HTTP/1.0 caches. However, with the widespread adoption of HTTP/1.1 and the introduction of cache-control directives, the Pragma header has become obsolete. The cache-control directives such as "no-cache" and "no-store" are now the standard mechanisms for controlling caching behavior.

I think in order to align with the latest web standards and best practices by **removing the usage of the Pragma header** from the library.

Please let me know about your opinions? I am happy to make a PR :)

**Comment by EvanHahn** [comment]
Good idea.

Feel free to make a PR! Because this is a breaking change, please open it against the `v4` branch that I just created.

**Comment by EvanHahn** [comment]
Could you fork the repository and push to your fork?

**Comment by dani2819** [comment]
@EvanHahn oh yes, here you go: https://github.com/helmetjs/nocache/pull/26

**Comment by EvanHahn** [comment]
This has been deployed in `nocache@4.0.0`.
