### ISSUE TITLE
Cache-Control: private may enable caching in the browser

### ISSUE THREAD

**Issue by analog-nico** [helmetjs/nocache#4]
As described in the [RFC](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9.1) `Cache-Control: private` disables caching by CDNs etc. So far so good. However, it actually allows non-shared caches - the browser has one - to cache the file: `A private (non-shared) cache MAY cache the response.`

Although, the code lists all the other "don't cache" values I would expect that some browsers get confused and decide to do caching.

**Comment by EvanHahn** [comment]
Do you think we should drop the `private` directive?

**Comment by analog-nico** [comment]
IMO yes.

I did more reading about all that caching stuff and begun to understand why the common header combinations are used. E.g. `Expires` is used for old browsers and some CDNs like Fastly because they don't process the `Cache-Control` header. If a client actually processes the `Cache-Control` header you can expect that they understand all properties. Since you already use `no-cache no-store` you are already on the save side. And I think `must-revalidate` is only added for the migration period: Assume you did not use the `Cache-Control` at all in production. Some browser now have your resources in its cache. If you now start to use just `Cache-Control: no-store no-cache` the existing cache would still be used. So `must-revalidate` is added just for the time you introduced the `Cache-Control` header. Altogether that means the list of properties is not compiled with a "more is better" approach. Instead all of them are actually required. Adding `private`, however, seems to me like a "more is better" approach and since browser who understand `Cache-Control` also understand `private` they actually might do something you don't want.

**Comment by EvanHahn** [comment]
I think this line in the RFC is the kicker for me:

> A private (non-shared) cache MAY cache the response.

I'll remove it now.

(Also, @analog-nico, I'd appreciate your feedback in #6 if you have time.)
